Force pyasn1<0.5.0
Apparently, pysnmplib isn't fully compatible with the latest version of
pyasn1 (version 0.5.0), causing lots of stupid errors like this one,
inside the pyasn1 library:

TypeError: decodeMessageVersion.<locals>.<lambda>() takes 3 positional arguments but 4 were given