Regression test incorrect scavenge notification
It turns out that existing Zino clients (ritz, curitz, zino-argus-glue)
will crash whenever they receive a notification about a scavenged event.

It turns out that `Zino1NotificationProtocol.build_notification()`
incorrectly generates an extra state change notifications about an
event after the initial "scavenged" notification, claiming that the
event state changed from `embryonic` to `closed`.  This is incorrect
both because no such state change occurred (it's comparing to a non-
existant old event), and because the event no longer exists.

Existing clients do not seem to protect against this faulty notification
and tend to crash, because they have already evicted any information
about this event and fail when they try to query Zino about the non-
existent event ID.  Example error:

> zinolib.ritz.ProtocolError: (500, 'event "13226" does not exist')